apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: openunison-cli
spec:
  version: "_VERSION_"
  homepage: https://github.com/OpenUnison/openunison-cli
  shortDescription: "Login to a kubernetes cluster via OpenUnison"
  description: |
    kubectl exec plugin that will launch a browser to authenticate you 
    without having a pre-existing kubectl configuration file.  The first
    time you execute this plugin, include the host of your OpenUnison 
    server and the plugin will launch a browser and authenticate you.  As
    you work with kubectl it will keep your short-lived tokens updated and
    if they expire, automatically re-launch a browser window to authenticate
    you.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
    uri: https://nexus.tremolo.io/repository/_OU_CLI_DIR_/openunison-cli-_VERSION_-macos.zip
    sha256: _MAC_SHA_
    files:
    - from: "openunison-cli"
      to: "openunison-cli"
    - from: "LICENSE"
      to: "LICENSE"
    bin: openunison-cli
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - linux
    uri: https://nexus.tremolo.io/repository/_OU_CLI_DIR_/openunison-cli-_VERSION_-linux.zip
    sha256: _LINUX_SHA_
    files:
    - from: "openunison-cli"
      to: "openunison-cli"
    - from: "LICENSE"
      to: "LICENSE"
    bin: openunison-cli
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - windows
    uri: https://nexus.tremolo.io/repository/_OU_CLI_DIR_/openunison-cli-_VERSION_-win.zip
    sha256: _WIN_SHA_
    files:
    - from: "openunison-cli.exe"
      to: "openunison-cli.exe"
    - from: "LICENSE"
      to: "LICENSE"
    bin: openunison-cli.exe