name: Build oulogin
on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ secrets.SESSION_NAME }}
          aws-region: us-east-1
      - run: ./build.sh ${{ secrets.S3_DIR }}
      # - name: Update new version in krew-index
      #   uses: rajatjindal/krew-release-bot@v0.0.46
        